require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.terminal")

require("plugins.autopairs")
require("plugins.colorscheme")
require("plugins.formatting")
require("plugins.fzf-lua")
require("plugins.gitsigns")
require("plugins.native-indent")
require("plugins.mason")
require("plugins.lsp")
require("plugins.nvim-tree")
require("plugins.diffview")
require("plugins.treesitter")
