set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # 'v' to begin selection
bind-key -T copy-mode-vi 'y' send -X copy-selection # 'y' to copy

unbind -T copy-mode-vi MouseDragEnd1Pane # Don't exit copy mode with mouse drag

set -sg escape-time 10 # Remove esc delay in Neovim
