require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.terminal")

require("plugins.autopairs")
require("plugins.colorscheme")
require("plugins.formatting")
require("plugins.fzf-lua")
require("plugins.gitsigns")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.nvim-tree")
require("plugins.mason")
require("plugins.neogit")
-- require("plugins.telescope")
require("plugins.treesitter")
